-- AlterTable
ALTER TABLE "hotel" ALTER COLUMN "hargaMax" SET DATA TYPE TEXT,
ALTER COLUMN "hargaMin" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "wisata" ALTER COLUMN "hargaMax" SET DATA TYPE TEXT,
ALTER COLUMN "hargaMin" SET DATA TYPE TEXT;
